name: deepwall_flutter_plugin
description: Deepwall Flutter plugin.
version: 3.0.1
homepage: https://www.deepwall.com/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  event_bus: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.deepwall.deepwall_flutter_plugin
        pluginClass: DeepwallFlutterPlugin
      ios:
        pluginClass: DeepwallFlutterPlugin
